In [16]:
import cv2
from tensorflow.keras.models import load_model
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
import numpy

In [17]:
face_cas = cv2.CascadeClassifier('haarcascade_frontalface_alt2 (1).xml')
face_cas

< cv2.CascadeClassifier 000001DE087EAD90>

In [18]:
model = load_model('mask_recog.h5')

In [19]:
def face_mask_detection(frame):
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    faces = face_cas.detectMultiScale(gray,minNeighbors=4)
    print(faces)
    for x,y,w,h in faces:
        face_frame = frame[y:y+h,x:x+w]
        #print(face_frame.shape)
    face_frame=cv2.cvtColor(face_frame, cv2.COLOR_BGR2RGB)
    face_frame=cv2.resize(face_frame,(224,224))
    face_frame=face_frame.reshape(1,224, 224,3)
    #print(face_frame)
    face_frame=preprocess_input (face_frame)
    #print(face_frame)
    pred=model.predict(face_frame)[0]
    print(pred)
    with_mask,without_mask=pred
    label="Mask" if with_mask>without_mask else "No mask"
    print(label)
    cv2.rectangle(frame,(x,y),(x+w,y+h),(0,0,255),3)
    cv2.putText(frame,label,(x,y),cv2.FONT_HERSHEY_COMPLEX,2,(255,0,0),2)
    return frame

In [20]:
img = cv2.imread('nomask.jpg')
result=face_mas_detection(img)
cv2.imshow("RESULT", result)
cv2.waitKey()
cv2.destroyAllWindows()

[[ 34  42 143 143]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[2.1002688e-07 9.9999976e-01]
No mask


In [ ]:
# Just Face detection
video = cv2.VideoCapture(0)
while True:
    suc,img=video.read()
    gray_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces=face_cas.detectMultiScale(gray_img)
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,2,34),3)
    cv2.imshow("WEBCAM",img)
    if cv2.waitKey(1) & 0XFF==ord('q'):
        break
video.release()
cv2.destroyAllWindows()

In [ ]:
# Mask Detection
video= cv2.VideoCapture(0)
while True:
    suc,img=video.read()
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cas.detectMultiScale(gray,minNeighbors=4)
    print(faces)
    for x,y,w,h in faces:
        face_frame = img[y:y+h,x:x+w]
        #print(face_frame.shape)
        face_frame=cv2.cvtColor(face_frame, cv2.COLOR_BGR2RGB)
        face_frame=cv2.resize(face_frame,(224,224))
        face_frame=face_frame.reshape(1,224, 224,3)
        #print(face_frame)
        face_frame=preprocess_input (face_frame)
        #print(face_frame)
        pred=model.predict(face_frame)[0]
        print(pred)
        with_mask,without_mask=pred
        label="Mask" if with_mask>without_mask else "No mask"
        print(label)
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,255),3)
        cv2.putText(img,label,(x,y),cv2.FONT_HERSHEY_COMPLEX,2,(255,0,0),2)
    cv2.imshow("WEBCAM",img)
    if cv2.waitKey(1) & 0XFF==ord('q'):
        break
video.release()
cv2.destroyAllWindows()

[[301 253 147 147]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
[0.7795066  0.22049344]
Mask
[[305 258 140 140]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
[0.7405142  0.25948578]
Mask
[[301 251 148 148]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
[0.83298135 0.16701862]
Mask
()
()
()
()
()
()
()
[[291 256 141 141]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
[0.95879734 0.04120265]
Mask
[[288 254 144 144]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
[0.9416952  0.05830476]
Mask
()
()
()
()
[[278 248 154 154]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
[0.91359127 0.0864087 ]
Mask
[[284 257 133 133]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
[0.5916153  0.40838474]
Mask
[[279 257 132 132]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
[0.9183554  0.08164461]
Mask
[[277 257 133 133]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
[0.69014466 0.30985537]
Mask
[[271 255 133 133]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
[0.10389091 0.8961091 ]
No mask
[[261 248 146 146]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
[0.01540265 0.9845974 ]
No mask
[[25